version: '3.8'
services:
  mysql:
    image: mysql:8.0.18
    ports:
      - '3306:3306'
    volumes:
      - ./data_mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:12.0-alpine
    environment:
    - POSTGRES_USER=app
    - POSTGRES_PASSWORD=pass

    ports:
    - '5432:5432'

    volumes:
      - ./data:/var/lib/postgresql/data

